### ISSUE TITLE
Wrong calm wind svg symbol?

### ISSUE THREAD

**Issue by alexandreleroux** [OGCMetOceanDWG/WorldWeatherSymbols#20]
Hi, I think the calm wind symbol might be wrong. Everywhere I looked, this symbol is a complete empty cercle. Currently, the symbol in this repos is a broken cercle, not complete:
ddff_WindArrows/WeatherSymbol_WMO_WindArrowCalm_00.svg

Can this issue be confirmed, and if so, then fixed? Thanks -- Alex

**Comment by chris-little** [comment]
Alex, Tom, and co,

I checked my original copy outside of GitHub, using Inkscape and it is a complete circle.

Also the SVG draws a complete circle. But the circle is bigger than the standard station circle used to display total cloud cover, so that the two together give the correct representation.

I think that the circle is being clipped to the original x-y square by the GitHub display package.

Option 1: Leave it as it is as the symbol probably displays elsewhere properly.

Option 2: Increase the coordinate ’extent’, so that GitHub does not clip it. This should be OK as the x-y coordinates are centred at the centre of the circle, but then it no longer has the same ‘nominal’ size as the other symbols.

Option 3: haven’t thought of one yet.

What are your thoughts?

Chris

**Comment by alexandreleroux** [comment]
Hi Chris, thanks for looking into it. I don't think the issue comes from the GitHub display. We have the same issue with a local copy of the file. I'm no svg expert, but I think the viewbox is smaller than the symbol and that's the source of the problem. The whole viewbox is 13.8 units large and the circle has a radius of 18 units. 18 >13.8 thus the symbol is truncated because it doesn't fit in the viewbox. Makes sense?

**Comment by chris-little** [comment]
Alex,

I played around in Inkscape and if we make the initial viewport 60x60 rather than 55x55, and mover the centre point of the circle to (30,30), it all fits neatly without clipping.

There is the same problem with WeatherSymbol_WMO_TotalCloudCover_Automatic.svg, which will need to be much bigger than 60x60. 92x92 with the triangle moved so its centroid is at about (46,46) looks OK.

I think that there are some other symbols with non-55x55 viewports.

Currently, until I have more time, I am reluctant to change them with Inkscape, as it is a bit random with its transforms, coordinates, snapping, metadata, etc

Chris

**Comment by chris-little** [comment]
And the 4 Tropical Cyclones.

From: Little, Chris
Sent: Thursday, March 05, 2015 10:20 AM
To: 'OGCMetOceanDWG/WorldWeatherSymbols'; OGCMetOceanDWG/WorldWeatherSymbols
Subject: RE: [WorldWeatherSymbols] Wrong calm wind svg symbol? (#20)

Alex,

I played around in Inkscape and if we make the initial viewport 60x60 rather than 55x55, and mover the centre point of the circle to (30,30), it all fits neatly without clipping.

There is the same problem with WeatherSymbol_WMO_TotalCloudCover_Automatic.svg, which will need to be much bigger than 60x60. 92x92 with the triangle moved so its centroid is at about (46,46) looks OK.

I think that there are some other symbols with non-55x55 viewports.

Currently, until I have more time, I am reluctant to change them with Inkscape, as it is a bit random with its transforms, coordinates, snapping, metadata, etc

Chris

**Comment by alexandreleroux** [comment]
I propose closing this ticket, since a fix for the calm wind symbol has been merged. If we want to address the issues you raise Chris regarding the other symbols, I suggest we open a new specific issue ticket -- Alex
