### ISSUE TITLE
Identifying target requirements for version 1.0

### ISSUE THREAD

**Issue by alexandreleroux** [OGCMetOceanDWG/WorldWeatherSymbols#21]
Tagging a version as 1.0 is a sign of maturity and will certainly attract more users and organizations to start using those symbols in their projects. Currently, we have some ideas identified in the TODO.txt file, but we don't currently have milestones or target requirements for eventually tagging a version 1.0.

My suggestion would be to create and discuss what improvements and changes should Version 1.0 of the WorldWeatherSymbols have. Without a clear path forward and a list of potential improvements, we won't reach maturity as quickly as we could. Thoughts / comments? Thanks -- Alex

**Comment by Voidrot-Martinez** [comment]
Hi Alex, 

I fully agree with your analysis 

Marie-francoise 
----- Météo-France ----- 
VOIDROT MARTINEZ MARIE-FRANCOISE 
DP/MSP 
marie-francoise.voidrot@meteo.fr 
Fixe : +33 561078127 
----- Mail original -----

De: "Alexandre Leroux" <notifications@github.com> 
À: "OGCMetOceanDWG/WorldWeatherSymbols" <WorldWeatherSymbols@noreply.github.com> 
Envoyé: Lundi 23 Février 2015 16:03:59 
Objet: [WorldWeatherSymbols] Identifying target requirements for version 1.0 (#21) 



Tagging a version as 1.0 is a sign of maturity and will certainly attract more users and organizations to start using those symbols in their projects. Currently, we have some ideas identified in the TODO.txt file, but we don't currently have milestones or target requirements for eventually tagging a version 1.0. 

My suggestion would be to create and discuss what improvements and changes should Version 1.0 of the WorldWeatherSymbols have. Without a clear path forward and a list of potential improvements, we won't reach maturity as quickly as we could. Thoughts / comments? Thanks -- Alex

**Comment by tomkralidis** [comment]
cc @chris-little

I have deleted https://github.com/OGCMetOceanDWG/WorldWeatherSymbols/blob/master/TODO.txt. and turned the content of it into GitHub issues.

I've also created a 1.0.0 milestone.

This way we can assign issues to milestones which help define the roadmap.

**Comment by chris-little** [comment]
Dear Colleagues,

Thanks to Alex and Tom for turning the repository into a cleaner GitHub. I’m sorry I have forgotten how to do GitHub stuff!


1.       I think the highest priority is to rotate all the wind arrows to N/S and this would merit a version 0.1 increase. This should be straightforward if tedious.



2.       I certainly agree that we should remove:
Unnecessary precision
Unnecessary groups (see 3. Below)
Unnecessary transformations
These were all consequences of manually creating them in Inkscape, and me learning to use Inkscape at the same time.
All of these would merit a 0.1 version increase.


3.       I thought about having each symbol as a group rather than an SVG, but then how do you easily display a single symbol? I suggest that we keep them as individual SVGs, with a single outer group, so that it becomes easier to strip out the SVG tags without altering default size and orientation.



4.       Trying to identify a minimal resolution/extent with integral coordinates is probably rather hard work, and I am happy to leave them majority of the symbols at 55x55. The extent has to be an odd number, to allow horizontal, vertical and diagonal centre lines.



5.       Choosing different origins, other than the centre point, for some symbols probably needs discussion among application developers. E.g. symbols like upper and medium cloud plotted centrally above the station circle would have an origin of bottom/centre. Low cloud would have top/centre. Present weather and past weather would all have centre/left. Etc.


I am now going back to preparation for Barcelona next week.

Cheers, Chris

**Comment by chris-little** [comment]
Dear All,

Ignore the error in (4) below. Obviously, to get a centre line, the size of a viewport/extent has to be an even number (e.g. xwidth = 54, origin at 0, xmin = -27, xmax = +27), so me making most of the initial viewports as 55x55 was rather stupid.

I apologise for thinking in pixels and not mathematics.

Shame on you all for not spotting my error. You all owe me a beer!

Chris

From: Little, Chris
Sent: Wednesday, March 04, 2015 6:03 PM
To: 'OGCMetOceanDWG/WorldWeatherSymbols'; OGCMetOceanDWG/WorldWeatherSymbols; Alexandre Leroux; 'Kralidis,Tom [Ontario]'; 'Marie-Francoise VOIDROT'
Subject: RE: [WorldWeatherSymbols] Identifying target requirements for version 1.0 (#21)

Dear Colleagues,

Thanks to Alex and Tom for turning the repository into a cleaner GitHub. I’m sorry I have forgotten how to do GitHub stuff!


1.       I think the highest priority is to rotate all the wind arrows to N/S and this would merit a version 0.1 increase. This should be straightforward if tedious.



2.       I certainly agree that we should remove:
Unnecessary precision
Unnecessary groups (see 3. Below)
Unnecessary transformations
These were all consequences of manually creating them in Inkscape, and me learning to use Inkscape at the same time.
All of these would merit a 0.1 version increase.


3.       I thought about having each symbol as a group rather than an SVG, but then how do you easily display a single symbol? I suggest that we keep them as individual SVGs, with a single outer group, so that it becomes easier to strip out the SVG tags without altering default size and orientation.



4.       Trying to identify a minimal resolution/extent with integral coordinates is probably rather hard work, and I am happy to leave them majority of the symbols at 55x55. The extent has to be an odd number, to allow horizontal, vertical and diagonal centre lines.



5.       Choosing different origins, other than the centre point, for some symbols probably needs discussion among application developers. E.g. symbols like upper and medium cloud plotted centrally above the station circle would have an origin of bottom/centre. Low cloud would have top/centre. Present weather and past weather would all have centre/left. Etc.


I am now going back to preparation for Barcelona next week.

Cheers, Chris
